### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by shikhar2402** [eubinecto/identify-idioms#8]
build.iip is not defined

![all](https://user-images.githubusercontent.com/46794327/117413761-f7c4e100-af33-11eb-9948-c7fb1c88d8f9.png)

**Comment by eubinecto** [comment]
Hey @shikhar2402, I thanks for pointing this out! It seems I forgot include an import statement in QuickStart, my apologizes.
 I've since updated README.md to include the one-liner. I hope you have fun with the library :)
